### ISSUE TITLE
Circular Redirects

### ISSUE THREAD

**Issue by t0ster** [mocleiri/github-oauth-plugin#13]
How to reproduce:

Go to Jenkins server (in my case http://myci.com:8080) than you will be redirected to github, press Allow than you will be redirected to Jenkins and again to github and so on.

**Comment by mocleiri** [comment]
What have you registered with github for the callback url?

It should read:  http://myci.com:8080/securityRealm/finishLogin

If you left off the /securityRealm/finishLogin part I could imagine it looping like you describe.

You can check the setting at: https://github.com/account/applications

**Comment by t0ster** [comment]
It was http://myci.com:8080

Thanks!

P.S: May be you should mention about this at https://wiki.jenkins-ci.org/display/JENKINS/Github+OAuth+Plugin

**Comment by mocleiri** [comment]
Thanks.  I've made some initial changes by creating a setup section on the plugin page.

**Comment by seabornlee** [comment]
I used to fix the problem according your tips. But I can make it working right now. 
![image](https://cloud.githubusercontent.com/assets/735708/13736319/74ec9b48-e9ee-11e5-94e6-b5470e2166ce.png)

In the nginx log, the weird part is the access to `/` of my ci server and return status is `403`.
