### ISSUE TITLE
Allow users to map their github username to commit username

### ISSUE THREAD

**Issue by mocleiri** [mocleiri/github-oauth-plugin#14]
Jenkins will summarize commits by users like in the change summary:

Commit xyz by _michael.ocleirigh_

But my github username is _mocleiri_ so this issue is about creating some type of equivalence so that things like build scoring plugins will work properly and track the correct users.

It seams that a custom UserProperty may work to hold the username part.

**Comment by jschementi** [comment]
This appears to be an still be an issue when "Configuration -> Git Plugin -> Create new accounts base on author/committer's email" is enabled - it would create an account with my git commit email as the username, and have another account with my GitHub username (created by this plugin). When disabling that Git plugin option and deleting the git-commit-email based usernames, this is not an issue - git commits were being associated with my GitHub username.

**Comment by mocleiri** [comment]
I'm no longer maintaining the plugin.  

@skottler is but using the main repository here: https://github.com/jenkinsci/github-oauth-plugin

Normally jenkins projects use jira for the issues but I never turned them off here.  But I think its confusing for reporters to report here. 

I want to turn off the issues on this repository so can you refile the ticket into the [jenkins jira for the _github-oauth_ component](https://issues.jenkins-ci.org/secure/IssueNavigator.jspa?reset=true&jqlQuery=project+%3D+JENKINS+AND+status+in+%28Open%2C+%22In+Progress%22%2C+Reopened%29+AND+component+%3D+%27github-oauth%27)?

Unfortunately there doesn't seem to be a way to make the existing issues _read-only_ so I can disable issues without all of the existing reported and resolved issues vanishing.

Thanks
