### ISSUE TITLE
"Comma separated list" is incorrect

### ISSUE THREAD

**Issue by p0deje** [mocleiri/github-oauth-plugin#15]
Let me first of all say thanks for this awesome plugin.

Help says that list for users with admin rights should be comma separated. But actually it should comma-space separated.
In case user entered something like `p0deje,github` - he'll loose admin rights and will have to stop Jenkins and manually edit `config.xml`.

It's better either to change documentation so it reflected that space is required or change behavior of `getAdminUserNames()`

https://github.com/jenkinsci/github-oauth-plugin/blob/master/src/main/java/org/jenkinsci/plugins/GithubAuthorizationStrategy.java#L121

**Comment by mocleiri** [comment]
Thanks for your feed back.

I think the comma space thing is just a rendering issue (i.e. I thought it looked nicer to have the space between the user names).

The ACL itself does a split on just the comma: https://github.com/jenkinsci/github-oauth-plugin/blob/master/src/main/java/org/jenkinsci/plugins/GithubRequireOrganizationMembershipACL.java#L198

look at line 201 and you will see I trim the parts.

**Comment by p0deje** [comment]
Oh, now I understand.

Still, when I enter `p0deje, some_other_user` to **Admin User Names**, I have admin rights.
But when I enter `p0deje,some_other_user` to **Admin User Names** I loose admin rights and have only READ permissions (just because I enabled **Grant READ permissions to all Authenticated Users**

Do you have any idea why could this happen?

**Comment by mocleiri** [comment]
I think this issue was fixed in the 0.9 plugin release.  What version of the plugin are you using?

**Comment by p0deje** [comment]
I use 0.9

**Comment by mocleiri** [comment]
I'm no longer maintaining the plugin.  

@skottler is but using the main repository here: https://github.com/jenkinsci/github-oauth-plugin

Normally jenkins projects use jira for the issues but I never turned them off here.  But I think its confusing for reporters to report here. 

I want to turn off the issues on this repository so can you refile the ticket into the [jenkins jira for the _github-oauth_ component](https://issues.jenkins-ci.org/secure/IssueNavigator.jspa?reset=true&jqlQuery=project+%3D+JENKINS+AND+status+in+%28Open%2C+%22In+Progress%22%2C+Reopened%29+AND+component+%3D+%27github-oauth%27)?

Unfortunately there doesn't seem to be a way to make the existing issues _read-only_ so I can disable issues without all of the existing reported and resolved issues vanishing.

Thanks
