### ISSUE TITLE
Feature request - Per-job authorization in Jenkins

### ISSUE THREAD

**Issue by davidjb** [mocleiri/github-oauth-plugin#17]
At the moment, the plugin allows for only two types of users: 
- Admin (can do anything in Jenkins; via "Admin User Names")
- 'Read' users (people that may have 'Read' permissions; eg Organization members, authenticated users, or Anonymous)

This is somewhat limiting in that you may have a number of different jobs/projects on the go, and want project-based security around this.  I'd like to allow for different users to have different permissions across projects.  For instance, be able to let certain users configure some jobs but not others, and be able to read/build some projects but not others.

Using something like the built-in 'Project-based Matrix Authorization Strategy' would be perfect, except that choosing this breaks the ability for GitHub to successfully communicate with '/github-webhook', which I would like to also use.

**Comment by mocleiri** [comment]
Thanks for your comments.

I created a new extension point in Jenkins to let the github-oauth-plugin wrap the global or project matrix authorization strategy to support things like the /github-webhook.

See: https://issues.jenkins-ci.org/browse/JENKINS-13190

Once this ticket is approved I will commit the code into the github-oauth-plugin to leverage it.  (basically the checkboxes would move up to the GithubSecurityRealm and transparently be applied in front of the selected AuthorizationStrategy).

**Comment by almostthor** [comment]
Would really love to see this move forward. Any chance that this can move forward?

**Comment by mocleiri** [comment]
I'm no longer maintaining the plugin.  

@skottler is but using the main repository here: https://github.com/jenkinsci/github-oauth-plugin

Normally jenkins projects use jira for the issues but I never turned them off here.  But I think its confusing for reporters to report here. 

I want to turn off the issues on this repository so can you refile the ticket into the [jenkins jira for the _github-oauth_ component](https://issues.jenkins-ci.org/secure/IssueNavigator.jspa?reset=true&jqlQuery=project+%3D+JENKINS+AND+status+in+%28Open%2C+%22In+Progress%22%2C+Reopened%29+AND+component+%3D+%27github-oauth%27)?

Unfortunately there doesn't seem to be a way to make the existing issues _read-only_ so I can disable issues without all of the existing reported and resolved issues vanishing.

Thanks
