### ISSUE TITLE
auth exception for jnlp access?

### ISSUE THREAD

**Issue by liamstask** [mocleiri/github-oauth-plugin#22]
Hi - thanks for this plugin!

Do you have any suggestions for how we should manage JNLP-based slave access to our public jenkins master node running the github oauth plugin? We're running our slaves on our local network, so this is an easy way for us to get the system set up.

Currently, I've just disabled oauth (and all) security during the initial setup of the slaves, but this will obviously not be too nice going forward.

It looks like the endpoint the slave tries to access is http://base_url.com/computer/slavename/slave-agent.jnlp.

Thanks for any suggestions!

**Comment by edmundsalvacion** [comment]
+1

**Comment by mocleiri** [comment]
I'm no longer maintaining the plugin.  

@skottler is but using the main repository here: https://github.com/jenkinsci/github-oauth-plugin

Normally jenkins projects use jira for the issues but I never turned them off here.  But I think its confusing for reporters to report here. 

I want to turn off the issues on this repository so can you refile the ticket into the [jenkins jira for the _github-oauth_ component](https://issues.jenkins-ci.org/secure/IssueNavigator.jspa?reset=true&jqlQuery=project+%3D+JENKINS+AND+status+in+%28Open%2C+%22In+Progress%22%2C+Reopened%29+AND+component+%3D+%27github-oauth%27)?

Unfortunately there doesn't seem to be a way to make the existing issues _read-only_ so I can disable issues without all of the existing reported and resolved issues vanishing.

Thanks
