### ISSUE TITLE
Makes Jenkins slow for non-admins

### ISSUE THREAD

**Issue by scribu** [mocleiri/github-oauth-plugin#23]
When I enable "Github Commiter Authorization Strategy", and I set up a few admin users from an organization, the non-admin users from that org get a long delay on each page load.

It seems as if Jenkins is hitting github every time to figure out if the user should have access.

**Comment by therod** [comment]
We are currently experiencing the same Issue  as described by  @scribu , but with delays up to 3 minutes. (22 Jobs configured)

**Comment by Iristyle** [comment]
+1 same problem

Have turned off the `Github Commiter Authorization Strategy` because it makes Jenkins unusable.

**Comment by mocleiri** [comment]
I'm no longer maintaining the plugin.  

@skottler is but using the main repository here: https://github.com/jenkinsci/github-oauth-plugin

Normally jenkins projects use jira for the issues but I never turned them off here.  But I think its confusing for reporters to report here. 

I want to turn off the issues on this repository so can you refile the ticket into the [jenkins jira for the _github-oauth_ component](https://issues.jenkins-ci.org/secure/IssueNavigator.jspa?reset=true&jqlQuery=project+%3D+JENKINS+AND+status+in+%28Open%2C+%22In+Progress%22%2C+Reopened%29+AND+component+%3D+%27github-oauth%27)?

Unfortunately there doesn't seem to be a way to make the existing issues _read-only_ so I can disable issues without all of the existing reported and resolved issues vanishing.

Thanks
