### ISSUE TITLE
404 errors immediately after implementing

### ISSUE THREAD

**Issue by adamrneary** [mocleiri/github-oauth-plugin#25]
I just switched over to the github-oauth plugin. I did include the format http://myserver.com:8080/securityRealm/finishLogin for the callback and simply http://myserver.com for the "url" in the github application settings.

within jenkins I provided my client id and secret, then switched to Github Commiter Authorization Strategy and clicked save.

This is not github enterprise, just the normal.

When I refreshed, it passed me to github for auth. I clicked allow, and then it routed me back to http://myserver.com, which promptly provided a 404. Have you seen this? Any thoughts?

**Comment by kohsuke** [comment]
I suspect maybe your "url" needs to be http://myserver.com:8080/ ?

**Comment by adamrneary** [comment]
@kohsuke sorry for leaving this open on you. I just just about to come on and close it. I am not sure what happened, but I stopped the server, deleted all the settings, restarted the server, re-entered all the settings, hit "go" and she worked fine. Sometimes it just something like that. Either way, we're up, and the plugin is killer. Thanks so much!

http://www.boston.com/partners/greader/prfmkt/images/GL15gronk333.jpg

**Comment by neezer** [comment]
Weird; I had the same issue. Blasting the preferences and setting it up again fresh did seem to work, as @adamrneary suggested.

**Comment by dblock** [comment]
Ran into the same problem. A jenkins service restart fixed it. I think it's either a bug though or a documentation problem at least.
