### ISSUE TITLE
Splitting out OAuth from GitHub API?

### ISSUE THREAD

**Issue by sodabrew** [mocleiri/github-oauth-plugin#27]
Hi, would it be possible to split apart the OAuth part of this plugin from the GitHub API? I'd like to use it for OAuth against other services, ideally without having to write a completely separate plugin (and end up with one for every service that provides OAuth...)

**Comment by mocleiri** [comment]
I don't know how easy this would be or not.  You can fork the plugin and see if you can split out the OAuth part for use with another service.

Basically if you can refactor things to suit your case I would be happy to merge a pull request that refactors the OAuth bits into a seperate artifact or plugin.

**Comment by sodabrew** [comment]
Put another way, I can't tell where your OAuth code ends, and the GitHub API pieces begin. The two should be absolutely orthogonal to one another, ideally handled by two separate plugins. My own unfamiliarity with Java plays into this, but the plugin structure isn't helping me much :/

Aha! Ok, I compared history on the GithubSecurityRealm.java file, and in the earlier revision it's a lot clearer what's happening. Could you help me understand, what's the marshalling and who calls the constructor with the URI arguments? Are those part of a configuration page?

Earlier and easier to follow:
https://github.com/mocleiri/github-oauth-plugin/blob/4e532c5af570e92a7f6fa32105e5c4324cb6bc58/src/main/java/org/jenkinsci/plugins/GithubSecurityRealm.java

vs. current master, and I don't get what's happening:
https://github.com/mocleiri/github-oauth-plugin/blob/master/src/main/java/org/jenkinsci/plugins/GithubSecurityRealm.java

Thanks!

**Comment by mocleiri** [comment]
I had another look at the code and the OAuth part is really very small. I'm not sure it makes sense to seperate but you can probably copy the approach I outline below to get the GithubSecurityRealm to work as an OAuthSecurityRealm or AnotherOAuthSecurityRealm.  I don't have experience with any other OAuth implementation to know if they work the same or not.

The github-api parts are basically using the oauth token to access the api to find out things about the user which is used to inform their authorization.

When using the github-oauth-plugin you configure the client id and secret id.

When a user tries to access a page they are redirected to the page specified on line 177: https://github.com/mocleiri/github-oauth-plugin/blob/4e532c5af570e92a7f6fa32105e5c4324cb6bc58/src/main/java/org/jenkinsci/plugins/GithubSecurityRealm.java#L177

The doCommenceLogin method handles that path: https://github.com/mocleiri/github-oauth-plugin/blob/4e532c5af570e92a7f6fa32105e5c4324cb6bc58/src/main/java/org/jenkinsci/plugins/GithubSecurityRealm.java#L79

And this forwards the users browser to github (attaching the client id) to the url.  This is where the user approves the application.

Then github redirects the users browser back to the url configured in the application setup. i.e. http://myserver/securityRealm/finishLogin

The doFinishLogin code runs at this point:
https://github.com/mocleiri/github-oauth-plugin/blob/4e532c5af570e92a7f6fa32105e5c4324cb6bc58/src/main/java/org/jenkinsci/plugins/GithubSecurityRealm.java#L97

This takes the code request parameter included in the link the user followed from github and then submits that with the client id and the secret as a post request back to github.

The response to this post is the OAuth token that can then be used to access the api as them.

https://github.com/mocleiri/github-oauth-plugin/blob/4e532c5af570e92a7f6fa32105e5c4324cb6bc58/src/main/java/org/jenkinsci/plugins/GithubSecurityRealm.java#L122

What application(s) are you looking to add support for?

**Comment by sodabrew** [comment]
Thanks!! (My specific need is Google Apps OAuth 2, but I want to do it in a generic OAuth 2 manner.)
