### ISSUE TITLE
404 for callback URL

### ISSUE THREAD

**Issue by ttback** [mocleiri/github-oauth-plugin#28]
Name: Name of app
URL: http://server:8080
Cacllback: http://server:8080/securityRealm/finishLogin

When i enable Github oAuth, it did pop up to say whether I want to allow this Appliation from Github, then I click Allow. 
So the authenticate step went through, but I hit 404 because The requested resource (/securityRealm/finishLogin) is not available.

There is nothing in Tomcat manager that says securityRealm, is there something else I need to set up to use this plugin?

**Comment by mocleiri** [comment]
I'm no longer maintaining the plugin.  

@skottler is but using the main repository here: https://github.com/jenkinsci/github-oauth-plugin

Normally jenkins projects use jira for the issues but I never turned them off here.  But I think its confusing for reporters to report here. 

I want to turn off the issues on this repository so can you refile the ticket into the [jenkins jira for the _github-oauth_ component](https://issues.jenkins-ci.org/secure/IssueNavigator.jspa?reset=true&jqlQuery=project+%3D+JENKINS+AND+status+in+%28Open%2C+%22In+Progress%22%2C+Reopened%29+AND+component+%3D+%27github-oauth%27)?

Unfortunately there doesn't seem to be a way to make the existing issues _read-only_ so I can disable issues without all of the existing reported and resolved issues vanishing.

Thanks
