### ISSUE TITLE
Project permissions according with organization groups.

### ISSUE THREAD

**Issue by gutomaia** [mocleiri/github-oauth-plugin#3]
Hi,

Indeed it is not a bug, it's more like a feature request.

My GitHub organization is divided in several groups. I would like to  allow build and read according with thouse groups.

Other matter is that some groups have some members hidden.  In the actual plugin, they all must be public.

:D

What is the road map for the next milestone?

**Comment by mocleiri** [comment]
Hi, 

What is needed for groups is a way to determine which groups a user belongs to using the github API 

I looked at something similar for the first version of the plugin but couldn't figure it out so I used the public membership test instead.

Your second part is also related to the github api.  If you can find a way to see hidden members of an organization then the authorization can be adapted to consider it.

Its possible that using a more privileged scope that more of the api will work and the features you want can be supported.

The 0.3 version will support the github-plugin build trigger but there are some serialization issues to fix before it can be released.

**Comment by appamatto** [comment]
I think I'm having the same issue--are you referring to organization teams?

When my team members log in to jenkins they get a message about a missing the Read permission.

**Comment by gutomaia** [comment]
Hi @mocleiri

I'm taking a look as you said, using github api, there seens to be a way of doing that.
look:
http://developer.github.com/v3/orgs/teams/

I will try to provide a demo. :D

@appamatto, this is not a BUG, but a feature request. I've never faces an error with this plugin :D

**Comment by scribu** [comment]
+1 for this

**Comment by aaronchi** [comment]
+1 Would like to limit read vs build access by team or user

**Comment by mocleiri** [comment]
I'm no longer maintaining the plugin.  

@skottler is but using the main repository here: https://github.com/jenkinsci/github-oauth-plugin

Normally jenkins projects use jira for the issues but I never turned them off here.  But I think its confusing for reporters to report here. 

I want to turn off the issues on this repository so can you refile the ticket into the [jenkins jira for the _github-oauth_ component](https://issues.jenkins-ci.org/secure/IssueNavigator.jspa?reset=true&jqlQuery=project+%3D+JENKINS+AND+status+in+%28Open%2C+%22In+Progress%22%2C+Reopened%29+AND+component+%3D+%27github-oauth%27)?

Unfortunately there doesn't seem to be a way to make the existing issues _read-only_ so I can disable issues without all of the existing reported and resolved issues vanishing.

Thanks
