### ISSUE TITLE
Breaks Jenkins SSH Server

### ISSUE THREAD

**Issue by ghost** [mocleiri/github-oauth-plugin#40]
Similar to #18, enabling _Github Authentication Plugin_ breaks the built in Jenkins SSH server, causing commands available via SSH to fail with `ClassCastException`. I'm running a sideloaded plugin built from hannonhill@9195edd18cda3df0f96d365156b13f421fafd686; the exception occurs on [`GithubSecurityRealm.java#L424`](https://github.com/hannonhill/github-oauth-plugin/blob/9195edd18cda3df0f96d365156b13f421fafd686/src/main/java/org/jenkinsci/plugins/GithubSecurityRealm.java#L424).
## Steps to Reproduce
1. Configure a user, adding an SSH public key
2. Enable _Github Authentication Plugin_
3. Run `who-am-i` command via SSH
   
   ``` shell
   ssh -p PORT the-dude@my.jenkins.abides who-am-i
   java.lang.ClassCastException: org.acegisecurity.providers.UsernamePasswordAuthenticationToken cannot be cast to org.jenkinsci.plugins.GithubAuthenticationToken
       at org.jenkinsci.plugins.GithubSecurityRealm.loadUserByUsername(GithubSecurityRealm.java:424)
       at hudson.model.User.impersonate(User.java:255)
       at org.jenkinsci.main.modules.sshd.CLICommandAdapter$1.run(CLICommandAdapter.java:31)
       at org.jenkinsci.main.modules.sshd.AsynchronousCommand$1.run(AsynchronousCommand.java:105)
       at java.lang.Thread.run(Thread.java:680)
   ```
## Expected Behavior

``` shell
ssh -p PORT the-dude@my.jenkins.abides who-am-i
Authenticated as: the-dude
Authorities:
  authenticated
```

**Comment by mocleiri** [comment]
I'm no longer maintaining the plugin.  

@skottler is but using the main repository here: https://github.com/jenkinsci/github-oauth-plugin

Normally jenkins projects use jira for the issues but I never turned them off here.  But I think its confusing for reporters to report here. 

I want to turn off the issues on this repository so can you refile the ticket into the [jenkins jira for the _github-oauth_ component](https://issues.jenkins-ci.org/secure/IssueNavigator.jspa?reset=true&jqlQuery=project+%3D+JENKINS+AND+status+in+%28Open%2C+%22In+Progress%22%2C+Reopened%29+AND+component+%3D+%27github-oauth%27)?

Unfortunately there doesn't seem to be a way to make the existing issues _read-only_ so I can disable issues without all of the existing reported and resolved issues vanishing.

Thanks

**Comment by hughsaunders** [comment]
@mocleiri you can now lock issues.
