### ISSUE TITLE
HTTP basic auth doesn't work for users != admin

### ISSUE THREAD

**Issue by finnq** [mocleiri/github-oauth-plugin#42]
Hi,

with this plugin the http basic auth with the api token only works for users who are listed under "Admin User Names". For other members of the github organisation it says: "Access Denied / [user] is missing the Overall/Read permission".

**Comment by skottler** [comment]
This issue should be fixed by now, but this also isn't the canonical bug tracker. Thanks for your report!

**Comment by popsikle** [comment]
This issue is not fixed. It is easily reproducible.
